version: "3"

services: 
  postgres:
    image: postgres:13
    init: true
    environment: 
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    init: true
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASWORD}
    ports:
      - "80:80"
    depends_on: 
      - postgres 

